# Generated by Django 5.1.4 on 2025-01-25 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_post_likes_like_post_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post_liked',
            new_name='post',
        ),
    ]
