# Generated by Django 5.1.4 on 2025-09-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0004_alter_follow_unique_together_like"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("liker", "liked")},
        ),
    ]
