{
  "name": "Python 3 & PostgreSQL",
  "dockerComposeFile": "docker-compose.yml",
  "service": "app",
  "workspaceFolder": "/workspace",
  "postCreateCommand": "pip install -r requirements.txt && python manage.py migrate",

  "extensions": [
    "ms-python.python",
    "mtxr.sqltools",
    "mtxr.sqltools-driver-pg"
  ],
  "settings": {
    "sqltools.connections": [
      {
        "name": "Container database",
        "driver": "PostgreSQL",
        "previewLimit": 50,
        "server": "db",
        "port": 5432,
        "database": "app",
        "username": "app_user",
        "password": "app_password"
      }
    ],
    "python.pythonPath": "/usr/local/bin/python"
  }
}
